- .eslintrc.json
- .prettierrc
- package-lock.json
- package.json
- src/App.tsx
- src/components/CoinTicker/CoinTicker.tsx
- 웹소켓으로 코인 시세 가져오기
- 라이브러리 추가 설치
- eslint, prettier 수정
-
-
>  merge : 웹소켓으로 코인 시세 가져오기 및 자잘한 수정

- src/components/Bookmarker/BookMarker.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/recoil/store.ts
- src/recoil/store.tsx
- BookMarker 웹소켓 로직 수정 원화 거래 코인 분류 데이터 받아오기 완료
-
-
- BookMarker.tsx
-
-
> chore: BookMarker 웹소켓 로직 수정 원화 거래 코인 분류

- src/components/CoinTicker/CoinTicker.tsx
- src/recoil/store.ts
- src/recoil/store.tsx
-  웹소켓 값 리코일에 저장하도록 수정
- 리코일내에서 마켓정보 가져오는 로직 수정
-
- components/CoinTicker.tsx
- /recoil/store.ts
-
> merge: 리코일 및 웹소켓 관련 코드 수정

- src/components/CoinTicker/CoinTicker.tsx
- src/recoil/atoms.ts
- CoinTicker 전일대비 가격 색상 CSS 추가
- Atoms 필요없는 코드 삭제
-
- atoms.ts
-
> merge: CoinTicker 전일대비 가격 색상 CSS 추가 / atoms 필요없는 코드 삭제

- public/index.html
- public/manifest.json
- src/components/CoinTicker/CoinTicker.tsx
- CoinTicker.tsx : html변경 및 조회 가능한 값 추가
- index.html : 필요없는 주석 삭제
-
- index.html
-
> merge: CoinTicker html 변경 및 index html 주석 삭제

- public/index.html
- src/App.tsx
- src/components/CoinTicker/AccTradePirce.tsx
- src/components/CoinTicker/CoinChange.tsx
- src/components/CoinTicker/CoinName.tsx
- src/components/CoinTicker/CoinPrice.tsx
- src/components/CoinTicker/CoinTicker.tsx
- 데이터 메모이제이션을 위한 CoinTicker 컴포넌트 세분화
-
-
-
-
> merge: CoinTicker 컴포넌트 세분화

- package-lock.json
- package.json
- src/App.tsx
- src/components/CoinDetail/CoinDetail.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/recoil/atoms.ts
- src/style/styled.d.ts
- Detail 컴포넌트 추가/ 데이터 연결, 일부 CSS 작성
-
-
- CoinDetail.tsx
-
-
> merge: Detail 컴포넌트 추가/차트 제외 데이터 연결

- src/Hooks/useGetCoins.ts
- src/components/CoinTicker/AccTradePirce.tsx
- src/components/CoinTicker/CoinChange.tsx
- src/components/CoinTicker/CoinListItem.tsx
- src/components/CoinTicker/CoinName.tsx
- src/components/CoinTicker/CoinPrice.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/recoil/atoms.ts
- 커스텀 훅으로 웹소켓, API통신 로직 분리
- CoinTicker 컴포넌트 렌더링 최적화
-
- useGetCoins.ts
-
> merge: 커스텀훅 추가 및 CoinTicker 컴포넌트 렌더링 최적화

- src/App.tsx
- src/components/Chart/CoinChart.tsx
- src/components/Chart/useGetInitialDataList.ts
- src/components/CoinDetail/CoinDetail.tsx
-KlineCharts 라이브러리 이용 샘플차트 작성 (BTC 일봉차트)
-
-
-CoinChart.tsx 
-
-
> feat: KlineCharts 라이브러리 이용 샘플차트 작성

- src/Hooks/useGetInitialDataList.ts
- src/Hooks/useNewData.ts
- src/components/Chart/CoinChart.tsx
- src/components/CoinDetail/CoinDetail.tsx
- src/components/CoinDetail/DetailNameBox.tsx
- src/components/CoinDetail/DetailPrice.tsx
- src/recoil/atoms.ts
- 차트 선택된코인 보여지게끔 연결
- 웹소켓 연결위한 세팅 (미완)
- 코인디테일 컴포넌트 작은단위로 분할
- useNewData.ts
- CoinChart.tsx
- CoinDetail.tsx
> feat: 차트 선택된코인 보여지기, 웹소켓 부분 연결, 디테일 컴포넌트 세분화

- src/Hooks/useGetInitialDataList.ts
- src/Hooks/useNewData.ts
- src/components/Chart/CoinChart.tsx
- 차트 웹소켓 실시간 업데이트 오류 해결 (초기값인 비트코인의 현재가로 업데이트 되던 현상 해결)
-
-
- useNewData.ts
-
-
> fix: 차트 웹소켓 실시간 업데이트 오류 해결

- src/App.tsx
- src/components/Chart/CoinChart.tsx
- src/components/CoinDetail/CoinDetail.tsx
- src/components/CoinDetail/DetailNameBox.tsx
- src/components/CoinTicker/CoinTicker.tsx
- 디테일,코인리스트 컨테이너 및 전체적인 스타일 적용
- 차트 캔들 스타일변경 버튼 추가(미완), style 적용
-
- CoinChart.tsx
-
-
> merge: 전체적 스타일 다듬기 , 차트캔들 스타일변경 기능 추가

- .gitattributes
- src/App.tsx
- src/Hooks/useGetCoins.ts
- src/Hooks/useGetInitialDataList.ts
- src/Hooks/useNewData.ts
- src/components/Bookmarker/BookMarker.tsx
- src/components/Chart/CoinChart.tsx
- src/components/CoinDetail/CoinDetail.tsx
- src/components/CoinDetail/DetailNameBox.tsx
- src/components/CoinDetail/DetailPrice.tsx
- src/components/CoinTicker/AccTradePirce.tsx
- src/components/CoinTicker/CoinChange.tsx
- src/components/CoinTicker/CoinListItem.tsx
- src/components/CoinTicker/CoinName.tsx
- src/components/CoinTicker/CoinPrice.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/recoil/atoms.ts
- src/types/types.tsx
- 타입선언 및 불필요한 코드 제거
- .gitattributes 생성
-
- .gitattributes
-
-
> refactor: 타입선언 및 불필요한 코드 제거 + .gitattributes 생성

- package.json
- src/Hooks/useAuth.ts
- src/Hooks/useGetCoins.ts
- src/Hooks/useGetInitialDataList.ts
- src/components/Bookmarker/BookMarker.tsx
- src/components/Chart/CoinChart.tsx
- src/components/CoinDetail/CoinDetail.tsx
- src/components/CoinDetail/DetailNameBox.tsx
- src/components/CoinDetail/DetailPrice.tsx
- src/components/CoinTicker/CoinListItem.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/components/Header/Header.tsx
- src/components/Header/Login.tsx
- src/components/Header/SignUp.tsx
- src/recoil/atoms.ts
- 회원가입 기능 추가
- 
-
- SignUp.tsx
-
-
> merge: 회원가입 기능 구현 및 폴더 네임 변경

- src/components/Chart/CoinChart.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/components/Header/Header.tsx
> merge: CSS 적용, 기존사항 수정

- src/App.tsx
- src/components/Bookmarker/BookMarker.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/components/Header/Header.tsx
- src/components/Header/Login.tsx
- src/components/portfolio/Portfolio.tsx
- 포트폴리오 기능 진행중 중간 PR
-
-
- Portfolio.tsx
- 
-
> merge: 포트폴리오 기능 진행 중 중간 PR

- src/Hooks/useAuth.ts
- src/components/Header/Header.tsx
- src/components/Header/Login.tsx
- src/components/Header/SignUp.tsx
- src/components/common/AbledBtn.tsx
- src/components/common/DisabledBtn.tsx
- Header 부분 CSS 수정 및 적용
-
-
- Header.tsx
- Login.tsx
- SignUp.tsx
> merge: Header 부분 CSS 수정 및 적용

- src/components/Bookmarker/BookMarker.tsx
- src/components/CoinTicker/CoinListItem.tsx
- src/components/Header/Header.tsx
- src/components/Header/Login.tsx
- src/components/Header/SignUp.tsx
- src/components/common/AbledBtn.tsx
- 회원가입 로그인 부분 로직 일부 수정, 전체적인 스타일 다듬기
-
-
- Header.tsx
-
-
> merge: 회원가입 로그인 부분 로직 일부 수정, 전체적인 스타일 다듬기

- src/App.tsx
- src/components/Bookmarker/BookMarker.tsx
- src/components/CoinDetail/CoinDetail.tsx
- src/components/CoinDetail/DetailNameBox.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/components/portfolio/Portfolio.tsx
- src/components/portfolio/PortfolioList.tsx
- src/components/portfolio/PortfolioPost.tsx
- src/style/GlobalStyle.tsx
- 포트폴리오 CSS 완료
- 북마크 기능 에러 해결
-
- Portfolio.tsx
- Bookmark.tsx
-
> merge: 북마크 기능 해결 / 포트폴리오 CSS 완료

- src/asset/svg/exclamation.svg
- src/components/Bookmarker/BookMarker.tsx
- src/components/CoinTicker/CoinTicker.tsx
- src/components/Header/Header.tsx
- src/components/portfolio/PortfolioPost.tsx
- src/style/GlobalStyle.tsx
- 로그인 여부에따라 리스트에 안내메세지와 이미지 출력
- UI 세부사항 수정
-
-
-
-
> refactor: 로그인 여부에 따른 주요기능 사용가능 제한 추가, UI 포함

- src/components/bookmarker/BookMarker.tsx
- src/components/chart/CoinChart.tsx
- src/components/coinDetail/CoinDetail.tsx
- src/components/coinDetail/DetailNameBox.tsx
- src/components/coinDetail/DetailPrice.tsx
- src/components/coinList/CoinCompare.tsx
- src/components/coinList/CoinList.tsx
- src/components/coinList/CoinListBody.tsx
- src/components/coinList/CoinListHeader.tsx
- src/components/coinList/CoinListItem.tsx
- src/components/coinList/CoinListNavbar.tsx
- src/components/coinList/CoinName.tsx
- src/components/coinList/CoinPrice.tsx
- src/components/coinList/CoinTradeVolume.tsx
- src/components/header/Header.tsx
- src/components/header/Login.tsx
- src/components/header/SignUp.tsx
- src/hooks/useAuth.ts
- src/hooks/useGetCoins.ts
- src/hooks/useGetInitialDataList.ts
- src/hooks/useNewData.ts
> fix: 깃 대소문자 구분 오류 세팅변경

- src/components/portfolio/PortfolioList.tsx
- src/components/portfolio/PortfolioPost.tsx
- src/hooks/useAuth.ts
- src/layout/CoinDetail.tsx
- src/layout/Header.tsx
- src/layout/Portfolio.tsx
- src/style/GlobalStyle.tsx
- src/types/types.ts
- any타입 변경 및 콘솔로그 삭제
-
-
-
-
-
> merge: any타입 변경 및 콘솔로그 삭제

- src/components/bookmarker/Marker.tsx
- src/components/chart/CoinChart.tsx
- src/components/coinList/CoinListBody.tsx
- src/components/coinList/CoinListNavbar.tsx
- src/components/common/AbledBtn.tsx
- src/components/common/DisabledBtn.tsx
- src/components/header/Login.tsx
- src/components/header/SignUp.tsx
- src/recoil/atoms.ts
- 전체적 미사용 코드 제거
- any 타입 올바르게 변경
-
-
-
-
> merge: any타입 변경 및 미사용 코드 제거

- src/components/bookmarker/Marker.tsx
- src/components/chart/CoinChart.tsx
- src/components/coinList/CoinListBody.tsx
- src/components/coinList/CoinListNavbar.tsx
- src/components/common/AbledBtn.tsx
- src/components/common/DisabledBtn.tsx
- src/components/header/Login.tsx
- src/components/header/SignUp.tsx
- src/components/portfolio/PortfolioList.tsx
- src/components/portfolio/PortfolioPost.tsx
- src/hooks/useAuth.ts
- src/layout/CoinDetail.tsx
- src/layout/Header.tsx
- src/layout/Portfolio.tsx
- src/recoil/atoms.ts
- src/style/GlobalStyle.tsx
- src/types/types.ts
- any타입 변경 및 콘솔로그, 필요없는 코드 삭제
-
-
-
-
-
> merge: any타입 변경 및 콘솔로그, 필요없는 코드 삭제

- src/components/chart/CoinChart.tsx
- 라이브러리 타입에러 수정
-
-
- Chart.tsx
-
-
> merge: 라이브러리 타입에러 수정

- src/components/coinList/CoinListItem.tsx
- src/hooks/bookmark/useGetBookmark.ts
- src/layout/Header.tsx
- src/service/API.ts
- 리프레시 토큰 만료 로직 수정 및 bookmark 요청 조건 추가
-
-
-
-
-
> fix: 리프레시 토큰 만료 로직 수정 및 bookmark 요청 조건 추가

- .eslintrc.json
- src/components/header/Login.tsx
- src/hooks/chart/useNewData.ts
- src/hooks/useGetMarkets.ts
- src/hooks/useLogout.ts
- src/layout/Header.tsx
- 리프레시 토큰 적용으로 인한 로그아웃 기능 버그 해결
-
-
-
-
-
> fix: 리프레시 토큰 적용으로 인한 로그아웃 기능 버그 해결

- src/hooks/chart/useGetInitCoinCandles.ts
> 백엔드 API 변경으로 재배포 하기위한 커밋
